### ISSUE TITLE
The path for `pedersen_params.json` is broken.

### ISSUE THREAD

**Issue by phramos07** [NethermindEth/caigo#100]
https://github.com/dontpanicdao/caigo/blob/9b016d75d4eb4dbe98a1a124edb4396daa693979/curve.go#L111

The correct path should be: 

https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/crypto/signature/pedersen_params.json

**Comment by gregoryguillou** [comment]
Hi @phramos07 , sorry for the delay. For rapid feedback check the `caigo` channel in the starknet discord.

It looks like that file has been removed month ago or am I missing something?

**Comment by gregoryguillou** [comment]
This issue should be fixed. If needed, pls contact us on the discord `#🦦 | caigo` channel.
