### ISSUE TITLE
Uint256 Examples Ignores 'High' field

### ISSUE THREAD

**Issue by rzmahmood** [NethermindEth/caigo#109]
Not sure if Caigo maintainers here but the example given in Caigo for `balanceOf` ignores the 'high' result for Uint256. See https://github.com/dontpanicdao/caigo/tree/main/examples/deploy
This is not a good idea as the high field could have a value. In JS, Immutable X does it like this https://github.com/immutable/imx-cairo/blob/main/tests/utils/starknetUtils.ts#L31

I'll look into making a PR if I have a capacity.

**Comment by tarrencev** [comment]
Thanks for flagging. I added the uint256 type in #110. If you have bandwidth to update the example, that would be greatly appreciated!

**Comment by rzmahmood** [comment]
I can update the example within the next 2-3 days @tarrencev
