### ISSUE TITLE
Unmarshalling compiled Cairo code into `ContractClass` fails 

### ISSUE THREAD

**Issue by rzmahmood** [NethermindEth/caigo#113]
Hey team. ContractClass expects a type string, but compiled Cairo Code outputs the "program" as an object. I need to do this because I want to deploy a contract using the JSON RPC

```go
type ContractClass struct {
	// Program A base64 representation of the compressed program code
	Program string `json:"program"`

	EntryPointsByType EntryPointsByType `json:"entry_points_by_type"`

	Abi *ABI `json:"abi,omitempty"`
}
```

This means when I try to do something like this:
```go
	compiledFile, err := os.Open(compiledERC20Path)
	assert.NoError(t, err)
	parser := json.NewDecoder(compiledFile)
	contractClass := caigorpctypes.ContractClass{}
	err = parser.Decode(&contractClass)
	assert.NoError(t, err)
```
It fails with the JSON object as in this pastebin, which is the compilation result of a minimal Cairo program of simply `%lang starknet`  : https://pastebin.com/UmmxGMze . 

The "program" part is an object, not a string and hence fails to Unmarshal. It fails with the error:
```
json: cannot unmarshal object into Go struct field ContractClass.program of type string
```

Any tips on resolving this would be great

**Comment by gregoryguillou** [comment]
Thank you @rzmahmood . #126 includes your fix to address that issue.
