### ISSUE TITLE
Bug: RPC Account WaitForTransaction never ends if transaction fails due to missing fees

### ISSUE THREAD

**Issue by rzmahmood** [NethermindEth/caigo#134]
I attempted to submit a transaction in the following two scenarios:

1. Fee added to execute payload but not enough balance -> Resulted in WaitForTransaction never-ending
2. No fee added to execute payload -> Resulted in WaitForTransaction never-ending

I was only able to figure out this was the issue as Starkscan shows when a TX is rejected due to no fee https://testnet.starkscan.co/tx/0x0018390ddc369f8c5bf66d94aa665df38e750f9b44c394e27e10a4a02e917715#overview

Voyager doesn't present this information.

If Starkscan is able to programmatically catch this scenario, then I'm sure there must be modifications we can make to Caigo to do the same.

**Comment by 0xLucqs** [comment]
I don't think this is a caigo error it's just that pathfinder nodes don't index rejected transactions. StarkScan indexes them because they rely on the sequencer

**Comment by drspacemn** [comment]
Yeah the RPC provider responds with:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": 25,
        "message": "Invalid transaction hash"
    },
    "id": 1
}
```
For this rejected transaction, and so never gets a valid TX status to check against in the `WaitForTransaction`. We could include a timeout as a short term solution. Pathfinder will return `REJECTED` TXs as of Cairo 1.0 which will be the long term solution.

**Comment by rzmahmood** [comment]
Thanks, makes sense. Timeout as the short term solution seems appropriate., but that can already be done with an appropriate `ctx context.Context` that has a timeout. Happy to leave this as is then.
