### ISSUE TITLE
Feature: Add Support for Devnet Mint and Mint Lite

### ISSUE THREAD

**Issue by rzmahmood** [NethermindEth/caigo#135]
The Shardlabs devnet allows for minting to an address using the local faucet -> https://github.com/Shard-Labs/starknet-devnet#mint-token---local-faucet

This is necessary when the deployed and funded accounts are not sufficient (e.g. wrong account contract).

It would be great to start adding support for devnet-specific functionality such as this.

**Comment by gregoryguillou** [comment]
Sorry, I did not see this issue. This is something we have this tests https://github.com/dontpanicdao/caigo/blob/5114a4722290c5f43dc1451942779fd21df40139/rpc/xsessions/plugin_test.go#L97 . I am not sure how to introduce that. Could we have a test hellper like `httptest` ?

**Comment by rzmahmood** [comment]
Resolving this due to added functionality
