### ISSUE TITLE
TestLocalStarkNet 403: unknown_error_format

### ISSUE THREAD

**Issue by rootulp** [NethermindEth/caigo#16]
I'm observing that local starknet tests fail. Is it possible there are additional setup instructions needed in the README?

```
=== RUN   TestLocalStarkNet
    starknet_test.go:86: Could not deploy contract: 403: unknown_error_format
    starknet_test.go:91: Could not get tx: 403: unknown_error_format
    starknet_test.go:96: Could not get tx receipt: 403: unknown_error_format
    starknet_test.go:101: Could not get block by hash: 403: unknown_error_format
    starknet_test.go:106: Could not get storage: 403: unknown_error_format
--- FAIL: TestLocalStarkNet (1.55s)
```

**Comment by tarrencev** [comment]
Hmm I haven't run it against local starknet instance. It seems to be returning a 403 though, is there some authentication necessary for the local api? Are you able to access the apis directly using curl?

**Comment by drspacemn** [comment]
I can add some extra documentation around it, but basically local devnet just needs to be up and accessible on port 5000

https://github.com/Shard-Labs/starknet-devnet

**Comment by rootulp** [comment]
Thanks for the hint. I tried running a starknet-devnet node and it is accessible on port 5000 but I haven't been able to issue a successful query to it and caigo tests continue to fail for likely the same reason.

Created https://github.com/Shard-Labs/starknet-devnet/issues/93

**Comment by drspacemn** [comment]
To make sure the caigo test pass(assuming you have docker) you can run:

`docker run -it --rm --network host shardlabs/starknet-devnet`

from caigo root dir

`go test -v ./...`

You should see the requests from caigo in the starknet-devnet logs

Also, there are postman collections here for the feeder_gateway and gateway endpoints:
https://www.postman.com/starknet-edu/workspace/starknet-edu

**Comment by rootulp** [comment]
```
docker run -it --rm --network host shardlabs/starknet-devnet
 * Listening on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

When running in `--network host` mode, the image claims to be listening on `http://0.0.0.0:5000/`, however `curl http://0.0.0.0:5000/is_alive` does not return a result. If I run the container via

```
docker run -p 127.0.0.1:5000:5000 shardlabs/starknet-devnet
```

then I'm able to successfully query `curl http://127.0.0.1:5000/is_alive` but I'm still observing `403` errors when running caigo tests

**Comment by drspacemn** [comment]
Can you try running the starknet-devnet without docker(`pip install starknet-devnet; starknet-devnet`) and then run/post the output of the following commands:
- `curl http://127.0.0.1:5000/is_alive`
-  `git log -n 1; go clean -testcache; go test ./...`

(note: if you're on the most recent commit and don't have pathfinder running you will see the JSON-RPC tests fail)

**Comment by rootulp** [comment]
Thanks for sharing these steps. `go test` succeeds when running starknet-devnet without Docker.

> curl http://127.0.0.1:5000/is_alive

Doesn't produce a result when running from Terminal but I can navigate to http://localhost:5000/is_alive and see "Alive!!!" in a browser.

> git log -n 1; go clean -testcache; go test ./...

```
git log -n 1; go clean -testcache; go test ./...
commit 2c585b42898a0e728f7855abae572a16973b878c (HEAD -> main, origin/main, origin/HEAD)
Merge: 5c31e23 7c1bfe0
Author: drspacemn <dontpanicdao@gmail.com>
Date:   Thu Apr 21 10:16:33 2022 -0600

    Merge pull request #13 from dontpanicdao/refactor/getters

    refactor account api





ok  	github.com/dontpanicdao/caigo	11.063s
```

I think this issue is safe to close. Thanks for all of your help!
