### ISSUE TITLE
500: StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT Entry point 0x1ac47721ee58ba2813c2a816bca188512839a00d3970f67c05eab986b14006d not found in contract 

### ISSUE THREAD

**Issue by XIAAMAN** [NethermindEth/caigo#183]
Your help is appreciated. Thanks.

**Comment by lajosdeme** [comment]
Hi! I'm getting the same error. Since I see you closed this issue, I imagine you were able to solve it. Could you help me understand how? @XIAAMAN

**Comment by lajosdeme** [comment]
OK, just figured it out.
In case anyone is having the same problem, you have to specify a version 1 account:

	acc, err := caigo.NewGatewayAccount(privateKey, address, gw, caigo.AccountVersion1)
	if err != nil {
		log.Fatal(err)
	}
