### ISSUE TITLE
[Test] Account package - test case set

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#215]
Fix tests in the contracts folder

**Comment by rianhughes** [comment]
https://github.com/NethermindEth/starknet.go/tree/FixContractTest

**Comment by rianhughes** [comment]
Should we just absorb this into the accounts package, by making the contract-methods methods of the accounts pkg?

**Comment by stranger80** [comment]
Let's rename this one, and assume this includes creating a "sensible" test case set for account package. Recommended to include a sample of Cairo 2.x contract code and operate on that contract code sample to prove it works with Starknet.go.

This test suite shall include:
- Declare Cairo contract to the network
- Unit test for methods moved from "contracts" folder (eg `WaitForTransaction()`)


Note: it may be sensible to have a single set of Cairo code "Assets"/artifacts, and refer to them from test cases, as well as library examples (in /examples folder).

**Comment by cicr99** [comment]
Adrressed by:
- #302 
- #386 
- #389
