### ISSUE TITLE
issue with Uint256 type and/or SplitFactStr

### ISSUE THREAD

**Issue by gregoryguillou** [NethermindEth/caigo#22]
I'm using Uint256 for ERC721 with Starknet and there is no direct support for that type in caigo. I do not know if that is something I should/could add, considering I'm also an adept of less is better. Uint256 is actually defined in the abi, maybe having an abigen as referenced in #1 would work better.

In the meantime, I am using `SplitFactStr` to `convert` the Uint256 into 2 Felt. I would like for the function to work even when the strings are shorter than 32-bytes. I've written a PR with the test that with the current code and succeed with the change. Can you review the PR and provide some feedback? 

Thank you for the project!

**Comment by drspacemn** [comment]
The PR/Test look good to me. I have merged it.

I will be working on #1 soon and can maybe provide another cleaner interface for what you're looking for

**Comment by gregoryguillou** [comment]
Thank you @drspacemn ! Uint256 could be part of the generated `struct` since it is defined in the abi file. #1 is definitely 💯 for me !

- if you are okay, I can probably start by contributing to the go doc. What do you think?
- is there a place we can interact? you might want to request for a channel on the starkware discord like it is the case for the other sdks.

2 comments:

- You might want to reduce the number of utils. For instance, We can use `.Text(10)` on *big.Int that is embed in the Felt rather than provide a separate implementation.
- I would argue to return `error` as part of the many interfaces. That will break things for the people already using the lib but that would be better.

**Comment by drspacemn** [comment]
Yup that is a good point. I actually work for StarkWare now so I can get that discord channel spun up. Also contributions on the godoc are definitely welcome

Comments:
1) Big fan of this 
2) Could you give me an example?

**Comment by gregoryguillou** [comment]
Thank you ! I'll provide some feedback. I think it would be very beneficial for Starknet that your project can be used a lot. Meanwhile I'll close this issue.
