### ISSUE TITLE
Add linter to github workflow

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#222]
Add a lint check to the github workflow. See https://github.com/NethermindEth/juno/blob/main/.github/workflows/juno-lint.yml

**Comment by rianhughes** [comment]
This likely requires fixing the tests first, as most linting errors are coming from broken tests.

**Comment by stranger80** [comment]
THis is duplicated by https://github.com/NethermindEth/starknet.go/issues/327
