### ISSUE TITLE
Specific type for `EventFilter.Keys` member

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/caigo#235]
- [ ] `EventFilter.Keys` is an array of array of felts instead of strings
- [ ] Add TOO_MANY_KEYS_IN_FILTER error

**Comment by rianhughes** [comment]
The code already has this [error](https://github.com/NethermindEth/starknet.go/blob/main/rpc/errors.go#L53) and the correct EventFilter.Keys [type](https://github.com/NethermindEth/starknet.go/blob/main/rpc/types_event.go#L35). Marking as closed.
