### ISSUE TITLE
Readme documentation link is broken

### ISSUE THREAD

**Issue by drknzz** [NethermindEth/caigo#242]
https://pkg.go.dev/github.com/dontpanicdao/starknet.go

**Comment by Bitcoinnoobie** [comment]
> https://pkg.go.dev/github.com/dontpanicdao/starknet.go

https://pkg.go.dev/github.com/dontpanicdao/caigo

maybe this old link will work

**Comment by rianhughes** [comment]
The documentation link is working for me, https://pkg.go.dev/github.com/NethermindEth/starknet.go. Is it still broken for you?

**Comment by drknzz** [comment]
> The documentation link is working for me, https://pkg.go.dev/github.com/NethermindEth/starknet.go. Is it still broken for you?

Yes, indeed this one is working.
There are 2 links in the readme, one for older repo - `dontpanicdao` and one for `NethermindEth`.
