### ISSUE TITLE
Errors when running the project locally，How to solve it?

### ISSUE THREAD

**Issue by LXHLeaner** [NethermindEth/caigo#247]
The err is this 
go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
	Remove the -mod flag to use the default readonly value,
	or set GOWORK=off to disable workspace mode.

**Comment by rianhughes** [comment]
Hey it seems that you have not specified the mod flag correctly, have you tried removing it? Also, it would be useful if you could provide more information regarding what you're trying to do, and the command you are executing etc.

**Comment by cicr99** [comment]
Hi @LXHLeaner! It's been a while since you opened this issue, can we assume it can be closed?
If you are still facing any difficulties, please let us know, we'd be happy to help
