### ISSUE TITLE
Create an AddDeployAccount Test

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#254]

**Comment by rianhughes** [comment]
For testnet:
https://github.com/NethermindEth/starknet.go/tree/RPCDeployAccountTest

**Comment by rianhughes** [comment]
Should also:
1. Readme starknet_addDeployTransaction should be updated to starknet_addDeployAccountTransaction
2. create a mock funciton etc

**Comment by mattcoburn24** [comment]
Hey @rianhughes can i work on this issue?

**Comment by rianhughes** [comment]
Sorry, I've already had to implement it for https://github.com/NethermindEth/starknet.go/issues/251 (still a WIP)
