### ISSUE TITLE
Bind RPC responses to errors

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#258]
RPC should return the appropriate errors, according to the spec (be sure to check both read and write APIs) https://github.com/starkware-libs/starknet-specs/blob/v0.2.1/api/starknet_api_openrpc.json

Hint: Some (all?) are marked by "// TODO bind"..

**Comment by mattcoburn24** [comment]
Hey @rianhughes I'd like to work on this issue.
