### ISSUE TITLE
Update starknet_estimateFee for RPCv03

### ISSUE THREAD

**Issue by greged93** [NethermindEth/caigo#266]
starknet_estimateFee parameters, results, and errors need updated for support of RPC v03 specs.
[v02 specs](https://github.com/starkware-libs/starknet-specs/blob/v0.2.0/api/starknet_api_openrpc.json#L432) vs [v03 specs](https://github.com/starkware-libs/starknet-specs/blob/v0.3.0/api/starknet_api_openrpc.json#L488).

**Comment by rianhughes** [comment]
Hey, I forgot you were working on this sorry. I've created a PR for this issue, but I'm happy to close it if you want to make your own :)

**Comment by greged93** [comment]
hey no worries Rian, go with your PR!
