### ISSUE TITLE
Prepare input for Docusaurus documentation

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#303]
See [docusaurus](https://docusaurus.io/), [Juno](https://github.com/NethermindEth/juno/tree/main/docs).

This task is to bring the Starknet.go source code comments to the level such that Docusaurus artifacts can be generated from them.
Also include the script required to generate the Docusaurus content.

**Comment by aquental** [comment]
Thanks, I'll start documenting it.

**Comment by aquental** [comment]
Created Pull Request ([#415](https://github.com/NethermindEth/starknet.go/pull/415))
