### ISSUE TITLE
Use Juno utils.Map

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#317]
Look into using juno/pkg/slices.go utils.Map in particular for things like HexArrToFelt(...)  etc

**Comment by Sah314** [comment]
Hello! can you please elaborate the issue a little bit. Thanks.

**Comment by rianhughes** [comment]
Sure, in starknet.go's util package we have helper functions like HexArrToFelt which apply a function over each element in an array. However, we could just use something like Junos Map function https://github.com/NethermindEth/juno/blob/main/utils/slices.go#L14.

**Comment by Bitcoinnoobie** [comment]
I would like to work on this issue.
