### ISSUE TITLE
use unwrapErr trhoughout the codebase

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#318]
Certain rpc methods use a switch statement to return rpc errors. However, we should use unwrapErr().

depends on https://github.com/NethermindEth/starknet.go/pull/316

**Comment by cicr99** [comment]
The function to be used is now called `tryUnwrapToRPCErr` which can be found [here](https://github.com/NethermindEth/starknet.go/blob/a3a745a7309046e1fdbd1d649c867c58759617ca/rpc/errors.go#L32C6-L32C23)
