### ISSUE TITLE
Release 0.4.5 - Full support for RPC v0.4

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/caigo#325]
**Note** this has been relabeled as 0.4.5 to align pkg.go.dev and github.com tags after a "premature" 0.4.4 publication.

Checklist:
- [x] Communicate the Release planned date with Mktg team
- [x] All features for RPC v0.4 implemented (all tasks in https://github.com/NethermindEth/starknet.go/issues/276 done)
- [x] `rpc` package tested
- [x] README.md updated:
    - [x] Methods in [RPC](https://github.com/NethermindEth/starknet.go#rpc) section
    - [x] Examples in [Getting Started](https://github.com/NethermindEth/starknet.go#getting-started) section
    - [x] Adding a section for our social media ?? (See with Marketing team)
- [x] All code merged to main and tagged
- [x] Write Release Notes
  - [x] Share Release Notes with Mktg team (highlight the main themes of the Release)
- [x] Publish release on pkg.go.dev (automatic after Release tag applied on Github.com)
- [x] Release announcement on:
    - [x] [#shared-starknet-go](https://demerzelsolutions.slack.com/archives/C05BYLL8CEN)
    - [x] [Telegram group](https://t.me/StarknetGo)
    - [x] Social Media (ask Marketing team)

**Comment by stranger80** [comment]
Do we want to label this as v0.4.3, so that we align the lib versioning with RPCv0.4.0?
