### ISSUE TITLE
Restructure code base

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/caigo#326]
NOTE: consider some standard layout of a Go repo, like https://github.com/golang-standards/project-layout , eg.: 
- [x] #372
- [x] #367
- [x] #365 
- [x] #307
- [x] #393
- [x] #380 
- [x] #378

**Comment by stranger80** [comment]
Referred to @JorikSchellekens to confirm removal of go-starknet and plugins folders.

**Comment by stranger80** [comment]
Confirmed, remove both
