### ISSUE TITLE
Error when importing starknet.go

### ISSUE THREAD

**Issue by sjxqqq** [NethermindEth/caigo#345]
When using starknet.go in the project, an error is always reported when importing:
go: github.com/NethermindEth/starknet.go@v0.2.1-0.20220620163912-1db2ca279608: parsing go.mod:
	module declares its path as: github.com/dontpanicdao/caigo
	        but was required as: github.com/NethermindEth/starknet.go

**Comment by rianhughes** [comment]
Thanks for bringing this up. This is a known issue, and will be resolved when we make a release for rpcv04 (which is the next step on the roadmap)

**Comment by cicr99** [comment]
Hi @sjxqqq!
This problem should have been fixed already. Just wanted to check  whether everything works ok for you now. If that's the case we'll be closing this issue
