### ISSUE TITLE
Update the environment varialbes 

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#497]
Integration base should be renamed
Should allow users to specify their public, private and account info via environment variables

**Comment by thiagodeev** [comment]
Hi @rianhughes, thanks for the suggestion. Sorry for the delay.
I agree. We'll update in the next release.

**Comment by thiagodeev** [comment]
Hi @rianhughes, thanks for the suggestion. Sorry for the delay.
 Are you talking about the `env.template` file located in each example of the "examples" folder? About this file also contain the user's account information instead of hardcode it?

**Comment by thiagodeev** [comment]
If I understood correctly, it's resolved at https://github.com/NethermindEth/starknet.go/pull/579/.
Please open another issue if it's not what you meant.
