### ISSUE TITLE
how to use EstimateFee

### ISSUE THREAD

**Issue by KillerJi** [NethermindEth/caigo#505]
Can someone give an example to use it? 
I don’t know how to convert it into the required format. I think usage examples should not directly use maxfee and omit the step of calculating fee.I need an example.

**Comment by ChiHaoLu** [comment]
Do you mean you don't know how to declare the input params of [`provider.EstimateGas`](https://github.com/NethermindEth/starknet.go/blob/915109ab5bc1c9c5bae7a71553a96e6665c0dcb2/rpc/contract.go#L140)?

If so, you should make sure to declare your variables in type `[]BroadcastTxn`, `[]SimulationFlag` and `BlockID` for function input. For example:
```golang
var broadcastTxn []BroadcastTxn
broadcastTxn.push(BroadcastTxn{
        // member declare ...
    }
)
```

However, you can specify the type with [these types](https://github.com/NethermindEth/starknet.go/blob/main/rpc/types_broadcast_transaction.go#L7).

And you figure out how does the input should look like [here](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/starkware-libs/starknet-specs/master/api/starknet_api_openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:darkMode%5D=true&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

**Comment by KillerJi** [comment]
> Do you mean you don't know how to declare the input params of [`provider.EstimateGas`](https://github.com/NethermindEth/starknet.go/blob/915109ab5bc1c9c5bae7a71553a96e6665c0dcb2/rpc/contract.go#L140)?
> 
> If so, you should make sure to declare your variables in type `[]BroadcastTxn`, `[]SimulationFlag` and `BlockID` for function input. For example:
> 
> ```go
> var broadcastTxn []BroadcastTxn
> broadcastTxn.push(BroadcastTxn{
>         // member declare ...
>     }
> )
> ```
> 
> However, you can specify the type with [these types](https://github.com/NethermindEth/starknet.go/blob/main/rpc/types_broadcast_transaction.go#L7).
> 
> And you figure out how does the input should look like [here](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/starkware-libs/starknet-specs/master/api/starknet_api_openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:darkMode%5D=true&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

Thanks for yr reply.Yes, I have discovered these parameter types before, but the problem is that I don’t know how to enter these parameters, such as maxfee. Why are the test examples inputted directly instead of estimated values? I obviously want to do a gas estimate. How do I know how much gas is required for the estimated action, so I need to have a transaction example, or give an example in advance. I think this is necessary for developers who are not 100% familiar with starknet development. Only if you know the gas estimate Only by estimating maxfee can we execute meaningful transactions, instead of just writing a random value of maxfee. What do you think?
