### ISSUE TITLE
Add an example that bridging ether from L1 to L2 and L2 to L1

### ISSUE THREAD

**Issue by ChiHaoLu** [NethermindEth/caigo#510]
I think it is helpful for **developers** who are new to StarkNet and starknet.go to know how to bridge ether from L1 to L2 and L2 to L1 at the contract-level instead of the StarkGate Website.

Hence I will make 2 PR for the:
1. The example of bridging ETH from Ethereum to StarkNet with using starknet.go to interact with StarkGate contract in Sepolia.
2. The example of bridging ETH from StarkNet to Ethereum with using starknet.go to interact with StarkGate contract in Sepolia.

In the **Example 1**, it should have the below progress.
1. Preprocessing
    - Load the [StarkGate address list](https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/sepolia.json).
    - Import the private key to control a deployed StarkNet account contract (L2 recipient).
    - Import the private key to control an Ethereum EOA (L1 sender).
    - Make sure the balance of the two accounts is enough.
2. L1
    - Call the [`deposit`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#deposit) on the L1 StarkGate Contract.
    - Wait for the `deposit` transaction to be mined.
3. L2
    - Triger the `handle_deposit` on the L2 StarkGate Contract.
        - **This behavior will be finished automatically by Sequencer**. It calls the `hadle_deposit` on the L2 StarkGate Contract and mints the token to the L2 recipient on their own.
        - **However, we still need to listen to the event emitting of the `deposit_handled`(or `Transfer`), or we cannot know when the transaction of `hadle_deposit` is finished.** (pls see [here](https://sepolia.starkscan.co/tx/0x0513492b5cfcd856f93827b367aa7dfcb570fbbd91bc5f964c7ce6e38f7242cb#events))
    - After the block that includes the `handle_deposit` transaction is proved, we can check the L2 recipient's ETH balance.

In the **Example 2**, it should have the below progress.
1. Preprocessing
    - Load the [StarkGate address list](https://github.com/starknet-io/starknet-addresses/blob/master/bridged_tokens/sepolia.json).
    - Import the private key to control a deployed StarkNet account contract (L2 sender).
    - Import the private key to control an Ethereum EOA (L1 recipient).
    - Make sure the balance of the two accounts is enough.
2. L2
    - Call the [`initiate_withdraw`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#initiate_withdraw) on the L2 StarkGate Contract.
    - Wait for the `initiate_withdraw` transaction to be mined.
3. L1
    - Waiting for the matching L2->L1 message (`WITHDRAW_MESSAGE`) to exist and be ready to be consumed.
    - Trigger [`withdraw`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#withdraw) on the L1 StarkGate Contract.
    - In the end, we check the l1 recipient ETH balance in this step.

**Comment by thiagodeev** [comment]
Hi @ChiHaoLu. Thanks for the suggestion. Sorry for the delay.
Indeed this is helpful, but the purpose of the examples is to guide the developers in their first steps with starknet-go, showing how to do common interactions with it, such as call a contract method, deploy an account, send an invoke transaction... 

Your suggestion is very specific, and I don't imagine it as the first thing someone would like to do with starknet-go. Of course, the more examples the better, but since it is too specific it's not our priority. If you or someone else could do it we appreciate it.

If I answered your question, please close the issue.
