### ISSUE TITLE
Examples - move user dependant variables to .env

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#529]
suggestion:

    move all variables that need to be replaced in .env.template file (all values are set with comment to replace it user .env file)
    add .gitignore in this directory with this content:

.env.*
!.env.template

this way user don't have to modify anything in code and is safe for comitting private data to some repo

**Comment by thiagodeev** [comment]
Already done and improved in https://github.com/NethermindEth/starknet.go/pull/579/
