### ISSUE TITLE
Start onlydust bounty to add starknet.go to starknet book

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#538]
start an onlydust bounty for putting starknet.go docs in the starknet book

https://app.onlydust.com/p/starknetgo

**Comment by mattcoburn24** [comment]
Hey @rianhughes I'd be interested in adding this section to the starknet book, what would i need to do to add the bounty with only dust?

**Comment by thiagodeev** [comment]
The starknet book is now [deprecated](https://github.com/starknet-edu/starknetbook?tab=readme-ov-file#the-starknet-book), and the current starknet documentation [quotes](https://docs.starknet.io/tools/devtools/#sdks) starknet.go
