### ISSUE TITLE
goerli depreceation

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#544]
Any tests and examples that currently use Goerli should use another test network, like Sepolia. 

1. Enter the rpc directory
2. rename .env.template to .env.testnet, and enter the Sepolia endpoint
3. go test ./... -env testnet

You will see a bunch of tests that currently depend on Goerli, but should be updated to depend on Sepolia instead.

Free RPC endpoints https://data.voyager.online/

**Comment by AryanGodara** [comment]
Hi @rianhughes can you please assign this issue to me.
We discussed this on the tg group : D I'll get started with it this weekend!
