### ISSUE TITLE
 adaptTransaction needs to account for non v1 Invoke transactions #1821 

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#552]
see here https://github.com/NethermindEth/starknet.go/blob/main/rpc/transaction.go#L30

This function should be able to handle v2 and v3 invoke transactions

**Comment by AryanGodara** [comment]
Hi, can I work on this @rianhughes :)

**Comment by thiagodeev** [comment]
Done at https://github.com/NethermindEth/starknet.go/pull/557.

https://github.com/NethermindEth/starknet.go/pull/557/files#diff-14aba5c63ad044ac1e8a62d96fed2cd132ad5e4935fc555a935a40c14f5cb0f7R42
