### ISSUE TITLE
Support for ByteArray Serialization

### ISSUE THREAD

**Issue by krishnateja262** [NethermindEth/caigo#580]
When interacting with a contract which takes in ByteArray as input, the `FunctionCall` takes only felt types as input. There is no support or I dont seem to find any utility for converting ByteArray to felt type.

**Comment by krishnateja262** [comment]
@thiagodeev I was able to do this and interact with the contract for taking byte arrays, happy to raise a PR for your review

**Comment by thiagodeev** [comment]
That's great @krishnateja262!
Are you talking about creating an example or a new feature?

**Comment by krishnateja262** [comment]
@thiagodeev thinking of it as a feature, i can write one helper function in `utils/Felt.go` file which will take a string and convert it to array of felts

**Comment by thiagodeev** [comment]
This would be very welcome! Please feel free to submit the PR.
Good resource: https://docs.starknet.io/architecture-and-concepts/smart-contracts/serialization-of-cairo-types/#serialization_of_byte_arrays

**Comment by krishnateja262** [comment]
@thiagodeev Raised #583
