### ISSUE TITLE
Consider to use stretchr instead of test-go

### ISSUE THREAD

**Issue by mdantonio** [NethermindEth/caigo#581]
I noticed that you are using [test-go/testify](https://github.com/test-go/testify) for test assertions (link to [go.mod](https://github.com/NethermindEth/starknet.go/blob/8e8eee2a1f31d26d0d6846a1e8443f6003776726/go.mod#L12C13-L12C28)).
This project is a pretty old fork of [stretchr/testify](https://github.com/stretchr/testify) and it looks to be no longer maintened (last commit is 7 years ago).
Curious to know if the fork includes some feature not available on the mainstream, otherwise I think you could consider to migrate to `stretchr`, that _should_ only require to change the import paths, if no specific functionalities from `test-go` are currently used)

Also note that on `contracts_test` it is mentioned that tests are based on `stretchr` ([ref](https://github.com/NethermindEth/starknet.go/blob/8e8eee2a1f31d26d0d6846a1e8443f6003776726/contracts/contracts_test.go#L40) and [ref](https://github.com/NethermindEth/starknet.go/blob/8e8eee2a1f31d26d0d6846a1e8443f6003776726/contracts/contracts_test.go#L61))

**Comment by thiagodeev** [comment]
Hi @mdantonio, thanks for pointing this out. It's a valid observation.
Since the fork is working without any issues, this is not a priority at the moment.
Could you open a PR about this? It would be welcome

**Comment by mdantonio** [comment]
Sure, here you are @thiagodeev https://github.com/NethermindEth/starknet.go/pull/582

**Comment by thiagodeev** [comment]
Done by @mdantonio at https://github.com/NethermindEth/starknet.go/pull/582. Thanks again

**Comment by mdantonio** [comment]
Nice, thank you!
