### ISSUE TITLE
Update the "Run Examples" instructions in the readme.md

### ISSUE THREAD

**Issue by thiagodeev** [NethermindEth/caigo#586]
This [section](https://github.com/NethermindEth/starknet.go?tab=readme-ov-file#run-examples) is outdated. It should be updated with the [new instructions](https://github.com/NethermindEth/starknet.go/tree/main/examples) contained in each example

**Comment by RV12R** [comment]
Assign it to me.

**Comment by PsychoPunkSage** [comment]
Looks like this issue can be closed now - the PR is merged!
