### ISSUE TITLE
update Juno version at go.mod file

### ISSUE THREAD

**Issue by thiagodeev** [NethermindEth/caigo#622]
Currently using Juno v0.3, but Juno is currently at v0.12. Let's update it

**Comment by lucky777strike** [comment]
Juno v0.3 uses github.com/sourcegraph/sourcegraph/lib v0.0.0-20221216004406-749998a2ac74 which moved to other repo and now for build i need use 
replace github.com/sourcegraph/sourcegraph/lib v0.0.0-20221216004406-749998a2ac74 => github.com/sourcegraph/sourcegraph-public-snapshot/lib v0.0.0-20221216004406-749998a2ac74
