### ISSUE TITLE
deploy and rely on the OZ account on testnet

### ISSUE THREAD

**Issue by gregoryguillou** [NethermindEth/caigo#76]
## Objective
Provide an example that deploys the (1) Openzeppelin account; (2) a ERC20 contract ; (3) mint ERC20 and (4) perform the transfer of a token to a 3rd party account with an Invoke

## Success Criteria
You might execute it with the Gateway API for now; you will need to be able:
- [ ] To deploy an account from Go (you should compile it first with the starknet CLI)
- [ ] To deploy an ERC20 contract from Go
- [ ] To document how to provide some ETH to the contract
- [ ] To mint the ERC20 from Go
- [ ] To Transfer some tokens to a separate account

## Additional notes
If you prefer to use the JSON RPC api, you might. However, there might be some missing pieces still, including the `starknet_getNonce`.

**Comment by greged93** [comment]
hey @gregoryguillou, can this one be closed or is there something to add?

**Comment by gregoryguillou** [comment]
Hi, we should have everything I guess. At least with the gateway:
- #95 prevents that PR from working fully
- I am guessing the `Declare/DeployContract` API are not working or at least not fully tested with RPC.

**Comment by greged93** [comment]
`Declare/DeployContract` are not tested for the RPC, I can have a go at it

**Comment by gregoryguillou** [comment]
> `Declare/DeployContract` are not tested for the RPC, I can have a go at it

Sorry. They should be now. And yes, you can move forward on that issue. You now have an account in the rpc directory
