### ISSUE TITLE
overflow for the value of key in (Gateway) `get_storage_at`

### ISSUE THREAD

**Issue by gregoryguillou** [NethermindEth/caigo#81]
[https://github.com/oxlime](oxlime) has made some tests on the gateway and reported an error in the type for `key` in the implementation of `get_storage_at` in the gateway. `key` is a uint64, yet, the value in the API can be larger than 64bits, see [this line in gateway/storage.go](https://github.com/dontpanicdao/caigo/blob/540e8a555ffbd991b9b6cc3c264227f4fe545a0c/gateway/storage.go#L20)

The reported issue is the following:

1. get_storage_var_address("erc20_crystal_address") is `475322019845212235330707245667153666023074534120350221048512561271566416926` which is obviously >64 bits
2. the following query succeed:

```shell
curl https://alpha4.starknet.io/feeder_gateway/get_storage_at?contractAddress=0x035401b96dc690eda2716068d3b03732d7c18af7c0327787660179108789d84f&key=475322019845212235330707245667153666023074534120350221048512561271566416926&blockNumber=281263

# "0x14a7a59e3e2d058d4c7c868e05907b2b49e324cc5b6af71182f008feb939e91"
```

Should we simply provide the key for now (i.e. base10 number as a string) or should we provide some abstraction as part of the API?

**Comment by drspacemn** [comment]
Gateway storage change from @oxlime has been merged 


https://github.com/dontpanicdao/caigo/blob/06e091c57d1c05c9451c57f67a5330880b955e37/gateway/storage.go#L27
