### ISSUE TITLE
Should Field `ChainId` in `Domain` be `*big.Int` or `string` instead of `int`?

### ISSUE THREAD

**Issue by phramos07** [NethermindEth/caigo#97]
Hello, everyone. I am building a `TypedData` in order to call `GetMessageHash` and generate a hash based on this data and an account address. 

However, the field `ChainId` in `Domain` is an `int`: 

```go
type Domain struct {
	Name    string
	Version string
	ChainId int
}
```

Shouldn't it be `*big.Int`? 

The reason is that the currently Starknet/Starkware values for the Mainnet/Testnet are as follows:
* Testnet (`SN_GOERLI`): `1536727068981429685321` or `0x534e5f474f45524c49` 
* Mainnet (`SN_MAIN`): `23448594291968334` or `0x534e5f4d41494e`

These values overflow an `int`. Testnet and Mainnet are `71 bits` and `55 bits` long respectively. How can I build a well-formed `TypedData.Domain` with the proper values for `ChainId` ?

**Comment by phramos07** [comment]
I suggest that [we adhere to `starknet.js` implementation](https://github.com/0xs34n/starknet.js/blob/b20819424dea824c96ac31e0542733c84d87d441/src/constants.ts#L11) and leave this field as `string`

```go
type Domain struct {
        ...
	ChainId string
}
```

and alter `FmtDefinitionEncoding` to convert the hex string to `big.Int`:

```go
func (dm Domain) FmtDefinitionEncoding(field string) (fmtEnc []*big.Int) {
	switch field {
        ...
	case "chainId":
		fmtEnc = append(fmtEnc, HexToBN(dm.ChainId))
	}
```

That way we can use these constants to provide the correct `big.Int` value:

```typescript
// starknet.js
export enum StarknetChainId {
  MAINNET = '0x534e5f4d41494e', // encodeShortString('SN_MAIN'),
  TESTNET = '0x534e5f474f45524c49', // encodeShortString('SN_GOERLI'),
}
```

**Comment by drspacemn** [comment]
Agreed we will get ChainId changed to string and will link the PR here

**Comment by SergeyVolynkin** [comment]
+1 🙌 thank you @phramos07

**Comment by gregoryguillou** [comment]
Can we close that @drspacemn?

**Comment by gregoryguillou** [comment]
I am guessing it is fixed. If not, it will be re-opened
